name: CI

on:
  push:
    branches:
      - main
    paths-ignore: # dont run when changes made to these folders
      - '.vscode/**'
  pull_request: {}
  workflow_dispatch:

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm prettier . --check

  package:
    name: Package
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3

      - name: fetch all history and tags from all branches for gitversion
        run: git fetch --prune --unshallow

      - name: DotNet Core SDK 3.1.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: install gitversion tool
        uses: gittools/actions/gitversion/setup@v0.9
        with:
          versionSpec: '5.5.x'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: execute gitversion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.7
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: print gitversion
        run: |
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"

      - name: update metadata in package.json
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: '${{github.workspace}}/package.json'
          patch-syntax: |
            = /version => "${{ steps.gitversion.outputs.majorMinorPatch }}"

      - name: add version in CHANGELOG.md
        uses: cschleiden/replace-tokens@v1.0
        with:
          files: '${{github.workspace}}/CHANGELOG.md'
        env:
          VERSION: "${{ steps.gitversion.outputs.majorMinorPatch }}"

      - name: compile and create vsix
        run: pnpm vs:package

      - name: upload vsix as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-ember-${{steps.gitversion.outputs.majorMinorPatch}}.vsix
          path: ${{github.workspace}}/vscode-ember-${{steps.gitversion.outputs.majorMinorPatch}}.vsix

      - name: create a release
        if: github.ref == 'refs/heads/main'
        continue-on-error: false
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.gitversion.outputs.semVer }}
          release_name: v${{ steps.gitversion.outputs.semVer }}

      - name: publish to marketplace VSCODE
        if: github.ref == 'refs/heads/main'
        env:
          VSCODE_STORE_TOKEN: ${{ secrets.VSCODE_STORE_TOKEN }}
        run: pnpm vs:publish:ci
        continue-on-error: true

      - name: publish to marketplace OPEN VSX
        if: github.ref == 'refs/heads/main'
        env:
          OPEN_VSX_STORE_TOKEN: ${{ secrets.OPEN_VSX_STORE_TOKEN }}
        run: pnpm ov:publish:ci
        continue-on-error: true
